services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- npx prisma migrate deploy && npm run seed && npm start"

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"  # Cambia el puerto expuesto en el host a 3307
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bd-prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
